### ISSUE TITLE
Error on boolean attributes when checked

### ISSUE THREAD

**Issue by titus-anromedonn** [josemlp91/staruml-django#3]
`code-generator.js` line `135` throws an error when you have a boolean and it is checked. This causes the rest of the models not to build. No fun :'(

Simply change `e.name` to `tag.name` and everything works. I verified this by modifying my local install.

```diff
      else if (tag.kind == 'boolean') {
        if (tag.checked) {
-          codeWriter.writeLine(e.name + '=True');
+          codeWriter.writeLine(tag.name + '=True');
        }
        else {
          codeWriter.writeLine(tag.name + '=False');
        }
      }
```

**Comment by josemlp91** [comment]
@titus-anromedonn, you're right, I will try to solve this issue for the next release. Thank you!

**Comment by josemlp91** [comment]
@titus-anromedonn 
![issue](https://user-images.githubusercontent.com/1655898/50492757-d07fb000-0a19-11e9-9dd8-14d546d15c77.png)
